Coordinate buffer
Trihydro/graphhopper pull request #1
Opened 2022-04-13 19:39 UTC by Globalgig

Not precisely where I want it to be, but this establishes the /buffer endpoint. There are a few required parameters that might get changed around, specifically like the queryMultiplier, and a few adjustments/TODO's that need to be resolved, but this version at least hasn't shown any of the previous bugs. The one big question lies with the Michigan left (as you can see the screaming emoji next to it), because, unlike the roundabout, I haven't found any tags that can help differentiate when that's happening, so currently there's a makeshift solution which *should* prevent it from taking said turns.

(Also, I've done 0 testing in the UK and that could feasibly break a lot of things)

TODO:
Add self to CONTRIBUTORS.md file
Add roadName sanitization
Swap over wayGeometry calculation
More tests?

2022-05-27 20:15 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +        while (true) {
Good idea, there's still the if statement at the bottom which is a little redundant, but that's there to ensure it doesn't move to the next point after hitting the threshold

2022-05-27 20:18 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +        List<Point> points = new ArrayList<Point>() {
I only made it so that it would return the points without keeping track of the path taken because I wanted to leave the /route endpoint logic separate (and therefore we'd have to use 2 API calls for the buffer and then for the routing given the point) but I'm fine with changing that if we want to

2022-05-27 20:18 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +    private final FlagEncoder flagEncoder;
Changed

2022-05-27 20:18 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +        // OLD LOGIC: BAD! Doesn't account for coming from a bidirectional road
Took that out

2022-05-27 20:19 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +                ;
Weird, took that out

2022-05-27 20:22 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +                if (Arrays.stream(queryRoadNames).anyMatch(roadName::equals)) {
You're right, I was planning on using the sanitize to trim of directionality and then using the equals, but now I'm thinking of leaving that out and using a .contains() or something

2022-05-27 20:22 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +class BufferFeature {
Moved to a new file

2022-05-27 20:23 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +    private static final Logger logger = LoggerFactory.getLogger(BufferResource.class);
That got left over when I was looking to some out resources for a starting point, took it out

2022-05-27 20:23 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +import com.graphhopper.util.shapes.GHPoint;
Removed

2022-05-27 20:25 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +            BufferFeature secondaryStartFeature = calculateSecondaryStartFeature(primaryStartFeature, roadName, .005);
This is the only comment I'm not really sure about. The calculateSecondaryStartFeature method generates a new bufferStartFeature method based off the primary where the two aren't touching, so they should be separate since the roads are distinct.

2022-05-27 20:28 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +    private BufferFeature calculatePrimaryStartFeature(Double startLat, Double startLon, String roadName,
I added comments at the top of most of the functions which are hopefully descriptive enough (but the michigan-left madness may have gotten to me and it might be incomprehensible)

2022-05-27 20:29 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +        for (Point point : points) {
Yeah, I swapped this over for a lineString because it's more intuitive that the buffer returns a list of two lines (even though, as described somewhere else, I'm only returning a start and endpoint instead of the whole geometry)

2022-06-03 17:45 UTC, payneBrandon commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +                if (Arrays.stream(queryRoadNames).anyMatch(roadName::equals)) {
The contains option could work, that way we remove the possibility of odd names passed in causing problems with an exact match. For instance directionality could be 'N', 'n', 'north', etc. depending on what the user has specified.

2022-06-03 17:50 UTC, payneBrandon commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +     * Given a lat/long, finds all nearby edges with a corresponding road name. Uses three expanding
Copy/pasta?

2022-06-03 17:58 UTC, payneBrandon requested changes
Just a couple comments

2022-06-21 18:33 UTC, Globalgig commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +     * Given a lat/long, finds all nearby edges with a corresponding road name. Uses three expanding
Good catch, I changed that now

2023-07-12 17:39 UTC, chansbtran approved these changes

2023-07-18 16:04 UTC, payneBrandon approved these changes

2023-07-18 16:12 UTC, merged