Fix master branch
Trihydro/graphhopper pull request #3
Opened 2023-07-20 20:32 UTC by chansbtran

Merging the buffer PR into Trihydro's fork of GH does not build successfully. This is due to the fact that FlagEncoder has been removed. This PR is to resolve those issues so we can build successfully.

Reference: https://github.com/graphhopper/graphhopper/pull/2611

2024-12-18 20:53 UTC, payneBrandon commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +            // TODO: do we want to remove all spaces from the names? There could be a mismatch between "I 80" "I-80" "I80" etc.
Probably appropriate in a method that sanitizes the names to return them in a consistent format. We'll want to update the description accordingly

2024-12-18 20:55 UTC, payneBrandon requested changes
Just the one comment

2024-12-18 21:18 UTC, tsweckard approved these changes

2024-12-18 22:41 UTC, chansbtran commented on web-bundle/src/main/java/com/graphhopper/resources/BufferResource.java
> +            // TODO: do we want to remove all spaces from the names? There could be a mismatch between "I 80" "I-80" "I80" etc.
Updated!

2024-12-19 16:47 UTC, payneBrandon approved these changes
lgtm!

2024-12-19 16:48 UTC, merged